"""
seed_flowers.py
Run this ONCE to pre-load all known DWG flowers into the database.
Usage: python seed_flowers.py

Safe to re-run — uses upsert so existing flowers are updated, not duplicated.
"""

import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault("DB_DIR", "/data" if os.path.isdir("/data") else ".")

from db.schema import init_db
from db.queries import upsert_flower

FLOWERS = [
    # (name, rarity, source, base_points, upgrade_cost)
    # ── BASIC ──
    ("Agastache",                  "Basic", "Garden Lv.",    0,  0),
    ("Asparagus Fern",             "Basic", "Garden Lv. 49", 0,  0),
    ("Blue Balloon Flower",        "Basic", "Garden Lv. 45", 0,  0),
    ("Blush-White Plumeria",       "Basic", "Garden Lv. 57", 0,  0),
    ("Bright Yellow Sunflower",    "Basic", "Garden Lv. 59", 9,  0),
    ("Canna",                      "Basic", "Garden Lv. 23", 9,  0),
    ("Cymbidium Orchid",           "Basic", "Garden Lv. 24", 9,  0),
    ("Daisy",                      "Basic", "Garden Lv.",    0,  0),
    ("Edelweiss",                  "Basic", "Garden Lv.",    0,  0),
    ("Eucalyptus Leaf",            "Basic", "Garden Lv.",    0,  0),
    ("Forget-Me-Not",              "Basic", "Garden Lv.",    0,  0),
    ("Golden Lucky Bamboo",        "Basic", "Garden Lv. 32", 0,  0),
    ("Green Pompon",               "Basic", "Garden Lv.",    0,  0),
    ("Hosta",                      "Basic", "Garden Lv. 37", 0,  0),
    ("Light Blue Moth Orchid",     "Basic", "Garden Lv. 30", 9,  0),
    ("Lily of the Valley",         "Basic", "Garden Lv.",    0,  0),
    ("Love Pea",                   "Basic", "Garden Lv. 27", 0,  0),
    ("Lucky Bamboo",               "Basic", "Garden Lv. 47", 9,  0),
    ("Mauve Gloxinia",             "Basic", "Garden Lv. 58", 0,  0),
    ("Monstera",                   "Basic", "Garden Lv. 52", 0,  0),
    ("Oleander",                   "Basic", "Garden Lv. 22", 0,  0),
    ("Orange Dahlia",              "Basic", "Garden Lv. 51", 0,  0),
    ("Orange Hibiscus",            "Basic", "Garden Lv. 38", 0,  0),
    ("Pale Blue Baby Blue Eyes",   "Basic", "Garden Lv. 42", 0,  0),
    ("Pale Blue Lupine",           "Basic", "Garden Lv. 54", 0,  0),
    ("Pale Pink Moth Orchid",      "Basic", "Garden Lv. 28", 0,  0),
    ("Pale Pink Petunia",          "Basic", "Garden Lv. 18", 0,  0),
    ("Pale Purple Baby Blue Eyes", "Basic", "Garden Lv. 44", 0,  0),
    ("Pansy",                      "Basic", "Garden Lv. 60", 0,  0),
    ("Pink Dahlia",                "Basic", "Garden Lv. 53", 0,  0),
    ("Pink Gladiolus",             "Basic", "Garden Lv. 33", 0,  0),
    ("Pink Lily",                  "Basic", "Garden Lv.",    0,  0),
    ("Pink Lupine",                "Basic", "Garden Lv. 19", 0,  0),
    ("Pink Rose",                  "Basic", "Garden Lv. 13", 0,  0),
    ("Pink Tulip",                 "Basic", "Garden Lv.",    0,  0),
    ("Plumeria",                   "Basic", "Garden Lv. 34", 0,  0),
    ("Purple Balloon Flower",      "Basic", "Garden Lv. 41", 0,  0),
    ("Purple Crane Flower",        "Basic", "Garden Lv. 56", 0,  0),
    ("Purple Daffodil",            "Basic", "Garden Lv. 46", 9,  27),
    ("Purple Gladiolus",           "Basic", "Garden Lv. 31", 0,  0),
    ("Purple Hibiscus",            "Basic", "Garden Lv. 40", 0,  0),
    ("Purple Petunia",             "Basic", "Garden Lv.",    0,  0),
    ("Rapeseed Flower",            "Basic", "Garden Lv.",    0,  0),
    ("Red Dahlia",                 "Basic", "Garden Lv. 55", 0,  0),
    ("Red Rose",                   "Basic", "Garden Lv.",    0,  0),
    ("Red Tulip",                  "Basic", "Garden Lv.",    0,  0),
    ("Snowdrop Lotus",             "Basic", "Garden Lv. 21", 0,  0),
    ("Tuberose",                   "Basic", "Garden Lv. 25", 0,  0),
    ("White Balloon Flower",       "Basic", "Garden Lv. 43", 0,  0),
    ("White Daffodil",             "Basic", "Garden Lv. 50", 0,  0),
    ("White Hibiscus",             "Basic", "Garden Lv. 36", 0,  0),
    ("White Lily",                 "Basic", "Garden Lv.",    0,  0),
    ("White Moth Orchid",          "Basic", "Garden Lv. 26", 9,  0),
    ("White Rose",                 "Basic", "Garden Lv.",    0,  0),
    ("Windmill Fruit",             "Basic", "Garden Lv. 29", 0,  0),
    ("Wintersweet",                "Basic", "Garden Lv. 39", 0,  0),
    ("Yellow Daffodil",            "Basic", "Garden Lv. 48", 0,  0),
    ("Yellow Gladiolus",           "Basic", "Garden Lv. 35", 0,  0),
    ("Yellow Petunia",             "Basic", "Garden Lv. 20", 0,  0),
    ("Yellow Tulip",               "Basic", "Garden Lv.",    0,  0),
    # ── FINE ──
    ("Blue Canterbury Bell",   "Fine", "Flower Shop",     0,  0),
    ("Blue Periwinkle",        "Fine", "Flower Shop",     0,  0),
    ("Blue Scabiosa",          "Fine", "Flower Shop",     0,  0),
    ("Bromeliad Flower",       "Fine", "Flower Benefits", 0,  0),
    ("Eryngo",                 "Fine", "VIP Shop",        14, 42),
    ("Fountain Grass",         "Fine", "Crystal Tree",    14, 0),
    ("Green Lachenalia",       "Fine", "Flower Shop",     0,  0),
    ("Lavender",               "Fine", "Flower Benefits", 0,  0),
    ("Orange Calla Lily",      "Fine", "Flower Shop",     0,  0),
    ("Orange Carnation",       "Fine", "Flower Benefits", 14, 0),
    ("Orange Lisianthus",      "Fine", "Flower Benefits", 0,  0),
    ("Orange Marigold",        "Fine", "Flower Shop",     0,  0),
    ("Orange Peace Lily",      "Fine", "Flower Shop",     0,  0),
    ("Orange Snapdragon",      "Fine", "Flower Shop",     0,  0),
    ("Ornamental Kale",        "Fine", "Floral Pass",     14, 42),
    ("Pink Blushing Bride",    "Fine", "Flower Benefits", 0,  0),
    ("Pink Calla Lily",        "Fine", "Flower Shop",     0,  0),
    ("Pink Carnation",         "Fine", "Flower Benefits", 0,  0),
    ("Pink Lotus",             "Fine", "Crystal Tree",    0,  0),
    ("Pink Periwinkle",        "Fine", "Flower Shop",     0,  0),
    ("Pink Snapdragon",        "Fine", "Flower Shop",     0,  0),
    ("Pink Zebra Primrose",    "Fine", "Flower Benefits", 0,  0),
    ("Purple Canterbury Bell", "Fine", "Flower Shop",     14, 42),
    ("Purple Carnation",       "Fine", "Flower Benefits", 0,  0),
    ("Purple Lisianthus",      "Fine", "Flower Benefits", 0,  0),
    ("Purple Nemesia",         "Fine", "Flower Shop",     14, 0),
    ("Red Camellia",           "Fine", "Crystal Tree",    0,  0),
    ("Red Kapok",              "Fine", "Flower Shop",     14, 42),
    ("Red Marigold",           "Fine", "Flower Shop",     0,  0),
    ("Velvet Flower",          "Fine", "Flower Benefits", 0,  0),
    ("White Azalea",           "Fine", "Flower Shop",     0,  0),
    ("White Baby's Breath",    "Fine", "Flower Shop",     0,  0),
    ("White Calla Lily",       "Fine", "Flower Shop",     0,  0),
    ("White Canterbury Bell",  "Fine", "Flower Shop",     0,  0),
    ("White Jasmine",          "Fine", "Flower Shop",     0,  0),
    ("White Peace Lily",       "Fine", "Flower Shop",     0,  0),
    ("White Snapdragon",       "Fine", "Flower Shop",     0,  0),
    ("White Zebra Primrose",   "Fine", "Flower Benefits", 0,  0),
    ("Winter Jasmine",         "Fine", "Garden Fair",     14, 0),
    ("Yellow Lachenalia",      "Fine", "Flower Shop",     0,  0),
    ("Yellow Marigold",        "Fine", "Flower Shop",     0,  0),
    # ── RARE ──
    ("Belle Blossom",              "Rare", "Dreamweaving Flower Theme Event", 23, 0),
    ("Blackberry Rose",            "Rare", "Flower Shop",                    20, 60),
    ("Blue Endless Summer",        "Rare", "Live Stream Flower Shopping",     0,  0),
    ("Blue Hyacinth",              "Rare", "Flower Shop",                    20, 0),
    ("Blue Lisianthus",            "Rare", "Flower Shop",                    0,  0),
    ("Blue Mallow",                "Rare", "Flower Shop",                    20, 0),
    ("Brocade Thorn Cluster",      "Rare", "Garden Fair",                    23, 0),
    ("Chamomile",                  "Rare", "7-Day Login",                    0,  0),
    ("Cloudpearl Sway",            "Rare", "Cumulative Top-Up Shop",         0,  0),
    ("Common Grape Hyacinth",      "Rare", "Floral Pass",                    23, 69),
    ("Cotton Plush Bear",          "Rare", "Flower Benefits",                0,  0),
    ("Evening Primrose",           "Rare", "Dreamweaving Path",              0,  0),
    ("Golden Gardenia",            "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Green Anthurium",            "Rare", "Flower Shop",                    20, 60),
    ("Green Cotton Flower",        "Rare", "Live Stream Flower Shopping",    23, 0),
    ("Green Pompon Chrysanthemum", "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Iridescent Rose",            "Rare", "Cumulative Top-Up Shop",         23, 0),
    ("Light Purple Periwinkle",    "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Light-Colored Peony",        "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Meowvellous",                "Rare", "Cumulative Top-Up Shop",         0,  0),
    ("Nebula Whisper",             "Rare", "Flower Shop",                    20, 0),
    ("Orange Cat's Claw Flower",   "Rare", "Flower Shop",                    0,  0),
    ("Orange Cockscomb",           "Rare", "Live Stream Flower Shopping",    23, 0),
    ("Orange Datura",              "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Orange Ixora",               "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Orange Mallow",              "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Orange Star Clivia",         "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Orchid Butterfly Dream",     "Rare", "Cumulative Top-Up Shop",         0,  0),
    ("Pale Blue Bougainvillea",    "Rare", "Crystal Tree",                   20, 60),
    ("Pale Pink African Violet",   "Rare", "Crystal Tree",                   0,  0),
    ("Pink Azalea",                "Rare", "Flower Shop",                    0,  0),
    ("Pink Baby's Breath",         "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Pink Bleeding Heart",        "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Pink Camellia",              "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Pink Cat's Claw Flower",     "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Pink Cotton Flower",         "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Pink Cyclamen",              "Rare", "Flower Shop",                    0,  0),
    ("Pink Endless Summer",        "Rare", "Flower Shop",                    20, 0),
    ("Pink Glory Lily",            "Rare", "Flower Shop",                    0,  0),
    ("Pink Hyacinth",              "Rare", "Flower Shop",                    20, 0),
    ("Pink Kapok",                 "Rare", "Flower Shop",                    0,  0),
    ("Pink Lantana",               "Rare", "Flower Shop",                    0,  0),
    ("Pink Mallow",                "Rare", "Flower Shop",                    0,  0),
    ("Pink Masterwort",            "Rare", "Flower Shop",                    0,  0),
    ("Pink Scabiosa",              "Rare", "Live Stream Flower Shopping",    23, 69),
    ("Pomegranate Flower",         "Rare", "Flower Shop",                    20, 60),
    ("Pure White Clivia",          "Rare", "Flower Shop",                    0,  0),
    ("Purple African Violet",      "Rare", "Crystal Tree",                   0,  0),
    ("Purple Anthurium",           "Rare", "Flower Shop",                    0,  0),
    ("Purple Azalea",              "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Purple Baby's Breath",       "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Purple Cat's Claw Flower",   "Rare", "Flower Shop",                    0,  0),
    ("Purple Cyclamen",            "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Purple Datura",              "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Purple Hyacinth",            "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Purple Lachenalia",          "Rare", "Live Stream Flower Shopping",    23, 0),
    ("Purple Lantana",             "Rare", "Flower Shop",                    0,  0),
    ("Purple Lotus",               "Rare", "Flower Shop",                    0,  0),
    ("Purple Masterwort",          "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Purple Meadowsweet",         "Rare", "Flower Shop",                    0,  0),
    ("Purple Scabiosa",            "Rare", "Live Stream Flower Shopping",    23, 0),
    ("Purple Zebra Primrose",      "Rare", "Flower Benefits",                0,  0),
    ("Rainbow Sunflower",          "Rare", "First Purchase Bonus",           0,  0),
    ("Red Anthurium",              "Rare", "Flower Shop",                    20, 0),
    ("Red Cockscomb",              "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Red Cyclamen",               "Rare", "Flower Shop",                    0,  0),
    ("Red Glory Lily",             "Rare", "Flower Shop",                    20, 60),
    ("Red Ixora",                  "Rare", "Live Stream Flower Shopping",    23, 0),
    ("Red Lantana",                "Rare", "Flower Shop",                    20, 0),
    ("Rose Red Peony",             "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Silver Leaf Kochia",         "Rare", "Cumulative Top-Up Shop",         0,  0),
    ("Snow Lotus",                 "Rare", "Cumulative Top-Up Shop",         0,  0),
    ("Verdant Pearl",              "Rare", "Dreamweaving Flower Theme Event",23, 69),
    ("White Bleeding Heart",       "Rare", "Live Stream Flower Shopping",    23, 0),
    ("White Blushing Bride",       "Rare", "Live Stream Flower Shopping",    0,  0),
    ("White Briar",                "Rare", "Flower Shop",                    0,  0),
    ("White Camellia",             "Rare", "Flower Shop",                    20, 0),
    ("White Cotton Flower",        "Rare", "Flower Shop",                    20, 0),
    ("White Datura",               "Rare", "Flower Shop",                    0,  0),
    ("White Endless Summer",       "Rare", "Live Stream Flower Shopping",    0,  0),
    ("White Gardenia",             "Rare", "Live Stream Flower Shopping",    0,  0),
    ("White Lotus",                "Rare", "Flower Shop",                    20, 0),
    ("White Masterwort",           "Rare", "Flower Shop",                    20, 0),
    ("White Meadowsweet",          "Rare", "Flower Shop",                    0,  0),
    ("White Red Spider Lily",      "Rare", "Crystal Tree",                   0,  0),
    ("Yellow African Violet",      "Rare", "Flower Shop",                    0,  0),
    ("Yellow Albizia Flower",      "Rare", "Live Stream Flower Shopping",    23, 69),
    ("Yellow Briar",               "Rare", "Flower Shop",                    20, 0),
    ("Yellow Clivia",              "Rare", "Flower Shop",                    0,  0),
    ("Yellow Cockscomb",           "Rare", "Live Stream Flower Shopping",    0,  0),
    ("Yellow Ixora",               "Rare", "Flower Shop",                    0,  0),
    ("Yellow Pompon Chrysanthemum","Rare", "Live Stream Flower Shopping",    0,  0),
    # ── STAR ──
    ("Azure Iris Dream",    "Star", "Live Stream Flower Shopping", 0,  0),
    ("Blushing Cloud Blossom","Star","Floral Bundle",              26, 0),
    ("Butterfly Vale",      "Star", "Dreamweaving Shop",          26, 0),
    ("Cloud Wish",          "Star", "Live Stream Flower Shopping", 26, 0),
    ("Crimson Gleam",       "Star", "Live Stream Flower Shopping", 26, 0),
    ("Crimson Sweet Pea",   "Star", "Live Stream Flower Shopping", 0,  0),
    ("Floral Sonata",       "Star", "Dreamweaving Shop",          26, 0),
    ("Golden Palace",       "Star", "Crystal Tree",               24, 72),
    ("Iris Violet Shadow",  "Star", "Live Stream Flower Shopping", 0,  0),
    ("Iris Waltz",          "Star", "Live Stream Flower Shopping", 0,  0),
    ("Lunar Jade Veil",     "Star", "Dreamweaving Shop",          26, 0),
    ("Palm Blessing",       "Star", "Live Stream Flower Shopping", 26, 0),
    ("River Teatree",       "Star", "Garden Fair",                26, 78),
    ("Royal Gleam",         "Star", "Live Stream Flower Shopping", 0,  0),
    ("Scarlet Othershore",  "Star", "Live Stream Flower Shopping", 0,  0),
    ("Seabreeze Sweet Pea", "Star", "Live Stream Flower Shopping", 0,  0),
    ("Starfall Dreamsea",   "Star", "Cumulative Top-Up Shop",     0,  0),
    ("Starlight Sway",      "Star", "Cumulative Top-Up Shop",     26, 0),
    ("Twilight Sweet Pea",  "Star", "Live Stream Flower Shopping", 0,  0),
    ("Violet Nightshore",   "Star", "Live Stream Flower Shopping", 26, 0),
    ("Zephyr Whisper",      "Star", "Live Stream Flower Shopping", 0,  0),
    # ── SHINE ──
    ("Butterfly Paw",          "Shine", "Cumulative Top-Up Shop", 32, 96),
    ("Dream - Fairy Tale",     "Shine", "Dreamweaving Shop",      28, 84),
    ("Glassheart",             "Shine", "Crystal Tree",           28, 84),
    ("Lion Dance Celebration", "Shine", "Garden Fair",            30, 90),
    ("Peachy Gilding",         "Shine", "Dreamweaving Shop",      30, 90),
    ("Pearl-Touched Sparrows", "Shine", "Cumulative Top-Up Shop", 34, 102),
    ("Vermillion Foxglow",     "Shine", "Dreamweaving Shop",      32, 96),
]

if __name__ == "__main__":
    init_db()
    count = 0
    for name, rarity, source, pts, cost in FLOWERS:
        upsert_flower(name, rarity, pts, cost, source)
        count += 1
    print(f"✅ Seeded {count} flowers into the database.")
